Dash Core: TransactionTablePriv Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
TransactionTablePriv Class Reference
Public Member Functions
TransactionTablePriv (CWallet *wallet, TransactionTableModel *parent)
void refreshWallet ()
void updateWallet (const uint256 &hash, int status, bool showTransaction)
int size ()
TransactionRecord * index (int idx)
QString describe (TransactionRecord *rec, int unit)
QString getTxHex (TransactionRecord *rec)
Public Attributes
CWallet * wallet
TransactionTableModel * parent
QList< TransactionRecord > cachedWallet
Detailed Description
Definition at line 59 of file transactiontablemodel.cpp.
Constructor & Destructor Documentation
TransactionTablePriv()
TransactionTablePriv::TransactionTablePriv (CWallet * wallet, TransactionTableModel * parent) inline
Definition at line 62 of file transactiontablemodel.cpp.
Member Function Documentation
describe()
QString TransactionTablePriv::describe (TransactionRecord * rec, int unit) inline
Definition at line 212 of file transactiontablemodel.cpp.
References cs_main, CWallet::cs_wallet, TransactionRecord::hash, LOCK2, CWallet::mapWallet, TransactionDesc::toHTML(), and wallet.
Referenced by TransactionTableModel::data().
getTxHex()
QString TransactionTablePriv::getTxHex (TransactionRecord * rec) inline
Definition at line 225 of file transactiontablemodel.cpp.
References cs_main, CWallet::cs_wallet, EncodeHexTx(), TransactionRecord::hash, LOCK2, CWallet::mapWallet, and wallet.
Referenced by TransactionTableModel::data().
index()
TransactionRecord* TransactionTablePriv::index (int idx) inline
Definition at line 180 of file transactiontablemodel.cpp.
References cachedWallet, cs_main, CWallet::cs_wallet, TransactionRecord::hash, CWallet::mapWallet, TransactionRecord::statusUpdateNeeded(), TRY_LOCK, TransactionRecord::updateStatus(), and wallet.
Referenced by TransactionView::computeSum(), TransactionView::contextualMenu(), and TransactionTableModel::index().
refreshWallet()
void TransactionTablePriv::refreshWallet () inline
Definition at line 79 of file transactiontablemodel.cpp.
References cachedWallet, cs_main, CWallet::cs_wallet, TransactionRecord::decomposeTransaction(), LOCK2, CWallet::mapWallet, TransactionRecord::showTransaction(), and wallet.
Referenced by TransactionTableModel::TransactionTableModel().
size()
int TransactionTablePriv::size () inline
Definition at line 175 of file transactiontablemodel.cpp.
References cachedWallet.
Referenced by TransactionTableModel::rowCount(), TransactionTableModel::updateConfirmations(), and TransactionTableModel::updateDisplayUnit().
updateWallet()
void TransactionTablePriv::updateWallet (const uint256 & hash, int status, bool showTransaction) inline
Definition at line 98 of file transactiontablemodel.cpp.
References cachedWallet, cs_main, CWallet::cs_wallet, CT_DELETED, CT_NEW, CT_UPDATED, TransactionRecord::decomposeTransaction(), LOCK2, CWallet::mapWallet, parent, base_blob< BITS >::ToString(), and wallet.
Referenced by TransactionTableModel::updateTransaction().
Member Data Documentation
cachedWallet
QList<TransactionRecord> TransactionTablePriv::cachedWallet
Definition at line 75 of file transactiontablemodel.cpp.
Referenced by index(), refreshWallet(), size(), and updateWallet().
parent
TransactionTableModel* TransactionTablePriv::parent
Definition at line 69 of file transactiontablemodel.cpp.
Referenced by updateWallet().
wallet
CWallet* TransactionTablePriv::wallet
Definition at line 68 of file transactiontablemodel.cpp.
Referenced by describe(), getTxHex(), index(), refreshWallet(), and updateWallet().
The documentation for this class was generated from the following file:
src/qt/transactiontablemodel.cpp
Released under the MIT license