Dash Core: CompareTxMemPoolEntryByDescendantScore Class Reference
Developers
Documentation
Guide
Reference
Examples
Glossary
Resources
Community
Vocabulary
Dash Core Source Documentation (0.12.2.2)
CompareTxMemPoolEntryByDescendantScore Class Reference
Sort an entry by max(score/size of entry's tx, score/size with all descendants).
#include <txmempool.h>
Public Member Functions
bool operator() (const CTxMemPoolEntry &a, const CTxMemPoolEntry &b) const
bool UseDescendantScore (const CTxMemPoolEntry &a) const
Detailed Description
Sort an entry by max(score/size of entry's tx, score/size with all descendants).
Definition at line 204 of file txmempool.h.
Member Function Documentation
operator()()
bool CompareTxMemPoolEntryByDescendantScore::operator() (const CTxMemPoolEntry & a, const CTxMemPoolEntry & b) const inline
Definition at line 207 of file txmempool.h.
References CTxMemPoolEntry::GetModFeesWithDescendants(), CTxMemPoolEntry::GetModifiedFee(), CTxMemPoolEntry::GetSizeWithDescendants(), CTxMemPoolEntry::GetTime(), CTxMemPoolEntry::GetTxSize(), and UseDescendantScore().
UseDescendantScore()
bool CompareTxMemPoolEntryByDescendantScore::UseDescendantScore (const CTxMemPoolEntry & a) const inline
Definition at line 229 of file txmempool.h.
References CTxMemPoolEntry::GetModFeesWithDescendants(), CTxMemPoolEntry::GetModifiedFee(), CTxMemPoolEntry::GetSizeWithDescendants(), and CTxMemPoolEntry::GetTxSize().
Referenced by operator()().
The documentation for this class was generated from the following file:
src/txmempool.h
Released under the MIT license